### ISSUE TITLE
how ignore errors adding folder recursively

### ISSUE THREAD

**Issue by cocodrino** [radovskyb/watcher#18]
Hello @radovskyb , hope you're fine, I'm having this error when I run a recursive watcher

```bash

error agregando directorio  open C:\$RECYCLE.BIN\S-1-5-18: Access is denied.

```

that means error adding a directory, after that the file walker seems exit because it doesn't add any other file

```golang

	i := 0
	fmt.Println(len(w.WatchedFiles()))
	fmt.Println("first 10 watched files are:")
	for path,_ := range w.WatchedFiles(){
		i+=1

		fmt.Println(path)
		if i>10{
			break
		}

	}

//print 0 
```

Could I ignore those files which cause error and keep running the file walker?

thank you so much!!!

**Comment by radovskyb** [comment]
Hey @cocodrino,

Sorry for the late reply!

Have you tried to ignore the folder or files that you want to ignore?

Here's an example for ignoring files or folders: https://github.com/radovskyb/watcher/blob/master/example/ignore_files/main.go

**Comment by radovskyb** [comment]
Hey @cocodrino,

I'm going to close this issue now but if you still have an issue or any other issues, feel free to let me know!
