### ISSUE TITLE
Consider Versioning

### ISSUE THREAD

**Issue by jeevatkm** [radovskyb/watcher#20]
@radovskyb Let me introduce myself. My name is Jeeva, I'm the author of [aah framework](https://aahframework.org). 

For upcoming release `v0.7` of my framework I'm working on Hot Reload functionality. I have been doing study and research around monitoring file and directory changes for a while. I know, there is a library `fsnotify`, it is good one. Then I come across your library, pretty interesting. **Good work**. 
  
I have evaluated your library for aah framework purpose and went through your code file. After that I'm leaning towards your library.

I would like to clarify following-
- Can you please version, tag and release your library per [semver.org](http://semver.org/), that I can binding to certain `git tag` via `gopkg.in`.
- If aah framework users come across any issues, are you okay to help out as best as you can. I know everyone has their priority. Even if delayed its fine, as long as their is solution/fix. I will try my best to send PR if I fix it.

If above points are not feasible (I'm hoping not), are you okay with forking your library into [go-aah](https://github.com/go-aah) org.

Please let me know. Thanks.

**Comment by jeevatkm** [comment]
@radovskyb any inputs?

**Comment by radovskyb** [comment]
Hey @jeevatkm,

I've tagged and added a release to Watcher. Let me know if I've missed something.

Sorry for the late reply!

Anyway, if you come across any issues, feel free to let me know. I haven't been as active on Github lately, but I'm still around :) Pull requests are always also welcome!

**Comment by jeevatkm** [comment]
@radovskyb Thanks for your response.

It is perfect, now `watcher` library is available `gopkg.in/radovskyb/watcher.v1` pointing to tag `v1.0.0`.
