### ISSUE TITLE
Option for ignoring exit > 0

### ISSUE THREAD

**Issue by tj** [radovskyb/watcher#21]
First thanks this is sweet! but for running tests I noticed if a test fails it'll exit entirely, an option to remain active would be handy

**Comment by radovskyb** [comment]
Hey @tj,

I never thought about a flag for ignoring errors, but I really like that idea :)

Will look into it when I get some time!

**Comment by radovskyb** [comment]
Hey @tj,

I've added a `keepalive` flag to allow watching to continue when a command exits with a non 0 status.

Let me know how it goes or if you have any other suggestions!
