### ISSUE TITLE
Option to clear screen

### ISSUE THREAD

**Issue by tj** [radovskyb/watcher#25]
It would be sweet to have an option to clear the screen so it doesn't create a busy looking list for while you're re-running tests. Via https://github.com/tj/go/blob/master/ansi/ansi.go#L6-L10 

Currently shorter output of course just continues to push the text lower and lower, just takes a bit more time to figure out what is the relevant output.

**Comment by radovskyb** [comment]
Hey @tj,

Sorry for the late reply!

Are you referring to clearing the screen in between individual events when running the watcher command?

Or if you mean clearing after poll cycles, currently there is only notifications for events and errors, but not when cycles begin and finish, so this could be slightly more difficult to implement.

Let me know your thoughts :)
