### ISSUE TITLE
Use watcher on virtualbox synced folders

### ISSUE THREAD

**Issue by julienkosinski** [radovskyb/watcher#26]
Hello,

@radovskyb Thank you very much for the great software!

I use Vagrant over Virtualbox with synced folder of type Virtualbox.
My host system is Windows 10 Creator's Update, my guest system is Ubuntu 16.04 with Go 1.8.3.
As described, watcher does not work with synced folders on Virtualbox if I trigger an event from the host OS in the synchronized folder while running watcher in the guest OS.

Is that logical? What should I do to workaround this?

Thank you! :)

**Comment by radovskyb** [comment]
Hey @julienkosinski, sorry for the late reply!

I'm not too sure I can help with this one as I'm unfamiliar with using Vagrant and don't really use Virtualbox much either so not sure how they are meant to interact with each other etc.

I'll leave this issue opened if you like and maybe someone with experience can help you.

**Comment by julienkosinski** [comment]
Thank you very much for your reply. :) I hope I'll find the solution of this but I don't know where to search...

**Comment by jeevatkm** [comment]
@radovskyb @julienkosinski I have verified this scenario.

My host machine Mac OS and vagrant VM of ubuntu. Watcher is able to detect the changes within VM and also host machine changes.

I don't have Windows OS host machine, so I'm unable to verify that. I have only Windows OS guest VM for aah framework testing purpose.

**Comment by julienkosinski** [comment]
Thank you very much for your help!

I'm running with the latest virtual box guest addition 5.1.26. Files and folder are synced correctly but no events are triggered, I can reproduce this on another computer with the same configuration as host, Windows Creator's Update.
I suppose this could be a bug in Virtualbox but I'll investigate a bit later on this :).

**Comment by julienkosinski** [comment]
@radovskyb @jeevatkm Thank you very much for you help!
Unfortunatly I did some research and it seems that this problem is related to virtualbox and filesystem. There's a known bug avoiding such events to work accross different filesystem.
https://www.virtualbox.org/ticket/10660

@jeevatkm What is strange though is that it is working on your side on MACOS. Do you have native driver for EXT filesystem in your host like OSXFUSE ?

**Comment by jeevatkm** [comment]
@julienkosinski I don't have any specific drivers. All I did was configuring `config.vm.synced_folder` in `Vagrantfile` and fired `aah run`. It's working at my end.

_Please Note: `watcher` library doesn't use native filesystem events._

**Comment by julienkosinski** [comment]
@jeevatkm Thank you for your response, as you said, I remembered now that watcher isn't relying on filesystem events, I think. So could be other thing.

**Comment by radovskyb** [comment]
Hey @jeevatkm, @julienkosinski,

Sorry a little late to the convo here. @jeevatkm, thanks for helping out with this issue.

@julienkosinski, it might be worth trying out fsnotify and seeing how you go with it if you haven't already given it a try, since that does use filesystem events.

**Comment by julienkosinski** [comment]
Hi @radovskyb, @jeevatkm!

Sorry for the delay...

I have news! :D
All event from synced folder are seen as WRITE events. The reason why I did not see this sooner is that I used the basic test in the exemple which by default limits to MOVE and RENAME events.

**Comment by radovskyb** [comment]
Hey @julienkosinski,

Glad to hear that you worked it out!

I probably should have asked to see the code from the beginning, but at least I'll remember if someone else comes along with the same question :P

I'll close this issue then since it sounds to me like it's been resolved :)

**Comment by julienkosinski** [comment]
@radovskyb Sorry, I forgot to response. Yeah, that's just some events which are not available in this configuration but I suppose that's normal. Thanks for your help! :D
