### ISSUE TITLE
Need a FINISH event

### ISSUE THREAD

**Issue by ShevaXu** [radovskyb/watcher#27]
I find it useful to have a FINISH event which fires when a newly created file finish being written. The use cases include automatically trigger processing when a file finishes downloading or being fully generated (e.g, some media file cannot be processed on the fly). 

The filesystem event notifications cannot solve this and polling is somehow required, which matches this watcher's polling nature. Should be a helpful feature?

**Comment by radovskyb** [comment]
Hey @ShevaXu,

Even though I can see the use cases, I'm not too sure that I would currently include this in watcher's core codebase as I'm trying to keep it quite minimal at the moment.

For example, using what watcher already includes you could probably achieve the finish event by actually using the library and checking for the constraints separately after each poll cycle.

Thanks for the suggestion though!

**Comment by ShevaXu** [comment]
Ok, I can understand your intent to keep it minimal. Also want to point it out that there's no way to note each poll cycle finishing so far. Anyway I will try to implement it myself, thanks.
