### ISSUE TITLE
Automatically execute cmd at start

### ISSUE THREAD

**Issue by gelidus** [radovskyb/watcher#28]
Is there a possibility to automatically execute cmd at the start of watcher? I am trying to use watcher with multiple microservices and it's painful to change every service for the first time just to get everything up.

**Comment by radovskyb** [comment]
Hey @gelidus,

It is currently not an option to execute the command automatically, however I like this suggestion and see it being very useful, so I will probably implement this within the next few days when I get some spare time!

**Comment by radovskyb** [comment]
Hey @gelidus,

I've added a really simple flag that allows you to run the command specified right before the watching process starts if you'd like to give it a go.

**Comment by gelidus** [comment]
Hi @radovskyb , thanks for the update! We'll try that and report back if we have any issues 👍
