### ISSUE TITLE
Renaming / Moving should return both files

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [radovskyb/watcher#29]
As per issue title, I believe it would be good to modify the events to return both the current file as well as the new one.

**Comment by felixbuenemann** [comment]
If you split the path in the `MOVE` event on ` -> ` you get the old and new path.

**Comment by radovskyb** [comment]
@Ewan-GrandSlam, sorry for the late reply!

@felixbuenemann is correct as both paths are returned :)
