### ISSUE TITLE
Support regular expressions as filters 

### ISSUE THREAD

**Issue by adragoset** [radovskyb/watcher#32]
Would be handy to be able to filter recursivley watching newly created files based on regular expressions. When watching a folder recursively it would be nice to be able to not set watches on subfolders or files that  get created but match a regular expression added to the filters list.

**Comment by radovskyb** [comment]
Hey @adragoset, sorry for the late response!

It is possible that I may add support for a filter function during the watching cycle as well as pre/post function hooks. I'm unsure how I want to currently implement these, but it may solve this issue for you if I do end up introducing it.

Feel free to submit any pull requests in the meantime if you like!

**Comment by radovskyb** [comment]
Hi @adragoset,

I have finally added some filter file hook functionality in commit cfaa0d64db472a0060a214ab9f115230841659cc.

Feel free to check it out as it now comes with a builtin RegexFilterHook function.
