### ISSUE TITLE
Issue with links to directories

### ISSUE THREAD

**Issue by linux-support** [radovskyb/watcher#34]
When there is link to a directory, containing a numer of files, watch does not recognice changes in that directory. Utilizing the same application to watch a dirctory without a link alle changed files will be recognized. 

Is this a bug, or are filesystem links not supported?

**Comment by radovskyb** [comment]
Hey @linux-support, this is currently not supported.

Right now for example, the `listRecursive` function uses the std lib's `filepath.Walk` function which does not follow sym links.
