### ISSUE TITLE
was AddRecursively removed from the source??? how ignore files and folders without permission???

### ISSUE THREAD

**Issue by cocodrino** [radovskyb/watcher#44]
Hello, hope you're great...I'm trying to follow the sample but I've two problems here

1) seems than AddRecursively was removed and Add doesnt watch recursively by default, how can I watch files recursively right now?
2) if I add the root folder I get some errors based on permission, would be possible skip those files than generates me errors???

thank you so much

**Comment by cocodrino** [comment]
ok my fault...I was using an old version of the package, after update I get the AddRecursively :dagger: 

but I keep my second question: How could I ignore those files that are not possible watch and don't break my code??? thank you!!!

**Comment by radovskyb** [comment]
Hi @cocodrino,

It may have appeared to be missing because it's actually `AddRecursive` and not `AddRecursively`.

There is also the method `Ignore` if you'd like to check that out.
