### ISSUE TITLE
Suggestion: the basic example confuses beginners easily

### ISSUE THREAD

**Issue by hsluoyz** [radovskyb/watcher#47]
I spent 20 minutes to figure out why the basic example doesn't work when I write to a file. Then I found these lines:

https://github.com/radovskyb/watcher/blob/0d9d32686dbf6395752c9b209398a59e302a7f1e/example/basics/main.go#L14-L21

So only one event per second is allowed, and only renaming and moving are shown.

This will easily make beginners confused, because I suppose the basic example should notify every event for me like a Hello-World for a file notification library.

If it is necessary to show these advanced use, It's better to comment them.

**Comment by radovskyb** [comment]
Hi @hsluoyz,

Thanks for your comments :)

How would you recommend that I reword the comment `Only notify rename and move events.` and the `SetMaxEvents` comments in the example to make it more clear?

**Comment by hsluoyz** [comment]
I think you can just comment them by default. Anyone needs this feature will uncomment it on his own. For example:

```go
 // Uncomment it to set SetMaxEvents to 1 to allow at most 1 event's to be received 
 // on the Event channel per watching cycle. 
 // 
 // If SetMaxEvents is not set, the default is to send all events. 
 // w.SetMaxEvents(1) 
  
 // Uncomment it to only notify rename and move events. 
 // w.FilterOps(watcher.Rename, watcher.Move) 
```

**Comment by radovskyb** [comment]
Hey @hsluoyz,

I've updated the basic example with your suggestions in commit d0ce736877937f3c7767434cf39e44d42253e522.

Thanks for the feedback!
