### ISSUE TITLE
Filewatcher hangs on error

### ISSUE THREAD

**Issue by Le-G** [radovskyb/watcher#48]
When encountering an error (in my case an ErrWatchedFileDeleted), the filewatcher seems to stop (even though it's not Closed, so I cannot restart it) and I'm not receiving any more events.

Is this a bug or am I not handling errors properly ?

My code looks very much like the examples provided, and I encounter this error because a temp file is quickly added and removed from the fs (and I just want to ignore it).

Thanks !

**Comment by Le-G** [comment]
Hi @radovskyb , thanks for your reply.

This is the code that instantiates and starts the filewatcher

```
	w := watcher.New()
	w.FilterOps(watcher.Create)
	go handleEvents(w, onSuccess)
	if err := w.AddRecursive(path); err != nil {
		log.Fatalln(err)
	}

	if err := w.Start(time.Second); err != nil {
		log.Fatalln(err)
	}

	done := make(chan bool)
	<-done
```


And this is the handleEvents func

```
func handleEvents(w *watcher.Watcher, onSuccess OnFileWritten) {
	for {
		select {
		case event := <-w.Event:
			if !isDir(event.Path) {
				log.Println("New file detected")
				done := make(chan bool)
				go waitForFileToFinishGrowing(event.Path, done)
				go func() {
					<-done
					onSuccess(event.Path)
				}()
			} else {
				w.Ignore(path.Join(event.Path, "index.m3u8"), path.Join(event.Path, "index.m3u8.bak"))
			}
		case <-w.Closed:
			log.Println("FileWatcher closed")
			return
		case e := <-w.Error:
			log.Printf("Error: %s", e)
		}
	}
}
```

As you can see, when a new directory is created I automatically want to ignore some kind of files which doesn't seem to work. They still end up being detected. I have no control over these files deletion and when they are deleted right after being detected, I get an error through the error channel.

The thing is, this error makes the filewatcher stop without closing it. I can't close it manually or restart it.

This code looks very similar to the example you provided and I can't figure out what's wrong with it.

Thanks for your help :)

**Comment by radovskyb** [comment]
Hey @Le-G,

It's a bit hard to replicate without a full working example and how to trigger the error you're receiving here, but I'll try and see if I can help anyway :)

It seems that the problem may lay elsewhere in your code. I'm not sure what `waitForFileToFinishGrowing` is doing, however I've created a working example from your code (With a couple of comment changes to simplify a couple of things that weren't needed in your example).

Here I am able to fully do the following.

Create a directory within the watched path, ignore a file, then lastly delete that file with no consequence. (starting from within `dir`, `mkdir new_dir`, then `cd new_dir`, then `touch index`, then `rm -f index`) 

If you are actually receiving the `ErrWatchedFileDeleted`, my guess is that you are either accidentally deleting the initial path that was added, or are somewhere else in your code using w.Add and then that file is being removed possibly.

	package main

	import (
		"fmt"
		"log"
		"path"
		"time"

		"github.com/radovskyb/watcher"
	)

	func onSuccess(path string) {
		fmt.Println("sucess", path)
	}

	func main() {
		path := "dir"

		w := watcher.New()
		w.FilterOps(watcher.Create)

		go handleEvents(w, onSuccess)

		if err := w.AddRecursive(path); err != nil {
			log.Fatalln(err)
		}

		if err := w.Start(time.Second); err != nil {
			log.Fatalln(err)
		}

		// w.Start is synchronous so the next 2 lines aren't actually needed.
		//
		// done := make(chan bool)
		// <-done
	}

	func handleEvents(w *watcher.Watcher, onSuccess func(string)) {
		for {
			select {
			case event := <-w.Event:
				if !event.IsDir() { // Event has access to IsDir method already so no need for isDir method.
					log.Println("New file detected")
					onSuccess(event.Path)
				} else {
					ignorePath := path.Join(event.Path, "index")
					fmt.Printf("ignoring %s\n", ignorePath)

					w.Ignore(ignorePath)
				}
			case <-w.Closed:
				log.Println("FileWatcher closed")
				return
			case e := <-w.Error:
				log.Printf("Error: %s", e)
			}
		}
	}

**Comment by Le-G** [comment]
Hi @radovskyb ,

`waitForFileToFinishGrowing` doesn't do much and doesn't interfere with the problem I'm referring to (it just stats the file until its size stops changing).

I've copy/pasted your code and was able to reproduce my error.
I only changed the `time.Second` interval to `100*time.Millisecond` (I initially increased that to a second because it makes it less likely to crash so decreasing it makes it easier to reproduce the error).

So, to reproduce my issue you just need to add and delete a file very quickly until it happens.
In my case running `repeat 10000 $(touch file && rm -f file)` in a watched directory does the trick.

When `Error: error: watched file or folder deleted` prints, nothing happens after that. The filewatcher isn't closed, Start() doesn't return and no new file is detected.

I hope this will make it easier for you to reproduce, please let me know if you need any more info.

Thanks for your help

**Comment by radovskyb** [comment]
Hi @Le-G,

I have actually been able to successfully reproduce the issue. I'm not sure off the top of my head what the issue is, but when I get some time I will try to look into it. Please let me know if you have any insights as well.

If you are able to write a unit test that can reproduce this issue, it will be much easier for me to fix as the problem is that the error is intermittent for me, but does not seem like any form of race condition.

I'll let you know of any updates! :)

**Comment by Le-G** [comment]
Hi,

Sorry I missed your reply !
Glad you could reproduce it as it's a bit tough to explain.

It seems like it's gonna be a pain to write a unit test to reproduce it as the issue is fairly random, but instead I'll try to have a look at the code to see if I can find any more info on where exactly it stops and on how it can be fixed.

Cheers !

**Comment by Le-G** [comment]
Hurray ! Found it ! 

In the retrieveFileList function, when you catch an error coming from retrieveFileList, you call the RemoveRecursive function on the parent directory (the one you called retrieveFileList on) instead of the path returned in the error (see example below). This causes the directory to be removed from the watch list.
As in my case it was the parent directory, the filewatcher was still running on... nothing :D

```for name, recursive := range w.names {
	if recursive {
		list, err = w.listRecursive(name)
		if err != nil {
			if os.IsNotExist(err) {
				w.Error <- ErrWatchedFileDeleted
				w.mu.Unlock()
				w.RemoveRecursive(name) // This is causing the issue. name should be replaced by err.(*os.PathError).Path
				w.mu.Lock()
			} else {
				w.Error <- err
			}
		}```

I'll fork and open a PR for that !

**Comment by radovskyb** [comment]
Hi @Le-G,

I'll have a look at your merge request soon :)

Good job finding a fix there.

I had a bit of a deeper look and I believe I know what is actually causing the initial error. The `listRecursive` function uses `filepath.Walk` and underneath `Walk`'s code, it reads each directory's file names and then tries to call `lstat` for each file, however if in between retrieving those names, the file is deleted, it will try calling `lstat` and it won't be there. That's my guess at least :)
