### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by amw863** [radovskyb/watcher#50]
Hi, radovskyb!

I am learning your code.  I cannot understand  these code :
````
go func() {
		w.Wait()
		w.TriggerEvent(watcher.Create, nil)
		w.TriggerEvent(watcher.Remove, nil)
	}()
````

https://github.com/radovskyb/watcher/blob/25a66c5e3b2606303dab04f005f1c276f0227f62/example/basics/main.go#L55-L59.

What I don't understand is why  ```w.Wait()``` can use more than once.  I searched by google, but no useful answer.  so, I hope get you help. 

Thank  you very much!

**Comment by Le-G** [comment]
If you look at the code, it tells you that "Wait blocks until the watcher is started."

In the snippet you shared, he created a goroutine that waits until the watcher is started, then sends two events (Create, and Remove).

It's pretty straightforward so I'm not sure what your question is and what you mean by "can use more than once"

**Comment by amw863** [comment]
I mean in the the two events why still call ```w.Wait()```.https://github.com/radovskyb/watcher/blob/25a66c5e3b/watcher.go#L397

In my opinion， this goroutine call ```w.Wait()``` for three times.

**Comment by radovskyb** [comment]
Hi @amw863,

You are correct that `w.Wait()` is called unnecessarily in the basic example as it will be called before `TriggerEvent` anyway :)

However, it's still in the example as a demonstration on how to wait for the watcher to be started before doing something else (which in this case is something that is already internally protected by `w.Wait()`)
