### ISSUE TITLE
Centos: SIGSEGV when change occurs with -cmd

### ISSUE THREAD

**Issue by TuulaP** [radovskyb/watcher#52]
Thanks for implementing this tool. I've been trying to get watcher to follow up what is happening in a specific directory, and simply just print number of files left. I added the counter shell to the -cmd, but directly after first change happens in the directory, I get a SIGSEGV error.  

> **watcher -dotfiles=false -recursive=false -cmd="./countzips.sh"**
> Watching 40 files
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4b550c]
> goroutine 6 [running]:
> os.(*ProcessState).os.success(...)
>         /usr/local/go/src/os/exec_posix.go:74
> os.(*ProcessState).Success(...)
>         /usr/local/go/src/os/exec.go:150
> main.main.func1(0xc42007a240, 0xc42008c000, 0xc420058280, 0x7ffd9483e732, 0xe, 0xc42000a070, 0x1, 0x1, 0xc4200160a4, 0xc4200160a5)
>         $HOME/go/src/github.com/radovskyb/watcher/cmd/watcher/main.go:76 +0x49c
> created by main.main
>         $HOME/go/src/github.com/radovskyb/watcher/cmd/watcher/main.go:56 +0x39a
> 

go version go1.10.3 linux/amd64 

The countzips.sh contains just `ls -1 *.zip | wc -l`

Is there something wrong with our Go installation, or did I just misunderstand how to utilize that cmd parameter? (Tried also having a go script for the counter, but got same message with that, too.)  All help is greatly appreciated.

**Comment by radovskyb** [comment]
I've updated watcher's command in commit 428d3583d221309651c70da500e00d80e578d0a7 where you would now get a message like the following instead of a panic.

`2018/12/11 10:31:00 fork/exec ./countzips.sh: exec format error`.
