### ISSUE TITLE
ignoreHidden not working on windows 

### ISSUE THREAD

**Issue by BITRU** [radovskyb/watcher#55]
Ignor hiden files not working on windows. 
I belive strings.HasPrefix(info.Name(), ".") work on linux, but not on windows.
On windows system app get stok for example on c:\System Volume Information
How to avoid this problem? 

2018/11/22 17:14:23 error: (EXTRA *os.PathError=open \\......\d$\System Volume Information: Access is denied.)

**Comment by radovskyb** [comment]
Hi @BITRU,

Are you sure that this is not a permissions issue?

Can you please paste your code so I can try to reproduce this? Thanks :)

**Comment by radovskyb** [comment]
Hey again @BITRU,

This issue should now be fixed with commit 3818ec23ec59ea15084fe26bfb114b3bb58aa132.

Please try it out and let me know how you go, thanks!
