### ISSUE TITLE
Close watcher

### ISSUE THREAD

**Issue by ericmdantas** [radovskyb/watcher#6]
Is there any way we can close the watcher? I was thinking that since we have `Start`, we could also have a `Close` method.

There's a module for Node.js called `chokidar` (https://github.com/paulmillr/chokidar) who does the following:

```
Methods and events
[...]
.close(): Removes all listeners from watched files
```

In my opinion, it'd make sense to have this in `watcher` too.

**Comment by radovskyb** [comment]
Hey @ericmdantas, I was actually thinking about this just the other day when I noticed that fsnotify also closes their watchers and thought it makes sense to add it.

I will hopefully get around to adding it when I have a bit of spare time over the next couple of days. I am glad you opened up an issue here though, so I will be reminded about it any time I see that there's an open issue!

**Comment by radovskyb** [comment]
Hey @ericmdantas, I've actually been planning on rewriting most of the `Start` method when I get some spare time, so I think I might just wait until I do that before I add a `Close` method, since the `Close` method will fit in better with the way that it's going to be rewritten anyway.

If for some reason you actually needed `Close` functionality for your project before I get around to it, either let me know and I'll just write something up that gets the job done temporarily until I rewrite the `Start` method, or just feel free to submit a PR.

**Comment by ericmdantas** [comment]
Hey, don't worry. I still have a couple things to figure out before releasing v1, so I can wait.

Let me know if I can help with anything.

**Comment by radovskyb** [comment]
Hey @ericmdantas,

I still haven't rewritten the `Start` method or any of the other code that I wanted to rewrite before adding in `Close`, but just had a bit of spare time so decided to just write a simple `Close` method in for now anyway.

There's a simple example for usage in the examples folder. Let me know how it goes if ya like!

**Comment by ericmdantas** [comment]
Will do, @radovskyb.

I'm on vacation now, but I'll be back next week. I'll let you know then.

Thanks for the heads up!

**Comment by im7mortal** [comment]
Hi! Thanks for your work!
<https://dave.cheney.net/2016/12/22/never-start-a-goroutine-without-knowing-how-it-will-stop>
I want to rephrase it like 
> Never start a infinite loop without knowing how it will stop

_Close_ method doesn't work for me. I don't have something special. Just such construction

```go
case <-time.NewTimer(15 * time.Second).C:
				w.Close() // deadlock
```

 I did a fast research. Looks like It can't pass lock <https://github.com/radovskyb/watcher/blob/master/watcher.go#L278>

# Fast solution for people who have it [HARDCODE]:heavy_exclamation_mark:

1. Define global var _Finish_ inside __ <https://github.com/radovskyb/watcher/blob/master/watcher.go>
2. Put such construction
```go
if Finish {
    return
}
```
here <https://github.com/radovskyb/watcher/blob/4231a17202a2c85e3d0037a5e55b3663ef0dcf75/watcher.go#L455>
3. Use _watcher.Finish = true_ when you want to end watching.

# Also 

I don't want to create a new issue.
Example from _README.md_ is wrong. It can misunderstood people. 

You use _WaitGroup_ for something. (In reality it's useless)
1. When I have seen it in first time I immediately did a assumption that inside _watcher.Start_ you use *gorutine* and _WaitGroup_ necessary for blocking _main gorutine_
2. But inside of _Start_ you use *infinite loop*:collision: which already block :no_entry: _main gorutine_
3. When execution will reach _wg.Wait()_ _wg.Done()_ will be triggered.

_WaitGroup_ is unused. It only misunderstood people. 
In first time  I put some code after _Start_. I spent some time before I that it was blocked:no_entry: .
Thank you for your work again!

**Comment by im7mortal** [comment]
about <https://github.com/radovskyb/watcher#example> and my previous comment's last paragraph
```go
// infinite loop don't block main gorutine
go func () {
	// Start the watching process - it'll check for changes every 100ms.
	if err := w.Start(time.Millisecond * 100); err != nil {
		log.Fatalln(err)
	}
}
// now WaitGroup has a sense
wg.Wait()
```

**Comment by radovskyb** [comment]
Hey @im7mortal, thanks for your comments.

I have actually realized both of the issues you have posted on here and have already written fixes for them in a different version of code that I have been writing in my spare time, however I've just been busy and there's still lots I have to do before I would push it to the main repo. 

For example, there's a Close channel, so in the main select loop, you know exactly when the watcher was closed so there is no goroutine leaks.

I'll get around to posting it eventually, there's just a lot that still needs to be done for it.

Kind Regards, Benji.

**Comment by im7mortal** [comment]
Hey @radovskyb 
On this weekend I am concentrated on your library.
Maybe you can push your code in **dev** branch ?
I am trying apply go pipeline patterns for your start function.
It would be great to combine our ideas!

**Comment by radovskyb** [comment]
Well currently it's very differently written and I haven't written the tests for it yet (the current tests need to be re-written for it), but also I have to benchmark it to see if some of it is worth keeping the way it will be.

I'll get around to posting it later if you would like to have a look.

P.S I already implemented piping the events in the new version I've been messing with, if that's what you mean by pipelines.

**Comment by radovskyb** [comment]
@im7mortal, I just created a dev branch with how I have been exploring rewriting watcher, but for now all of the tests and examples will be broken, but have a look if you're interested anyway :)

**Comment by im7mortal** [comment]
@radovskyb
I am going to create a new issue about future changes. 
Where I will describe all my ideas after I will take a look on your changes.

**Comment by radovskyb** [comment]
Hey @ericmdantas and @im7mortal, 

I've just updated the master branch with a lot of changes. One change fixes the Close method, so you can now check for `<-w.Closed` in the main function to avoid a goroutine leak.

P.S. There's also event filtering now if that's interesting to either of you (I added an example for it).

**Comment by ericmdantas** [comment]
Thanks for the heads up!

**Comment by im7mortal** [comment]
@radovskyb 
Maybe Instead `<-w.Closed` better would be `w.Done()` which return `<-chan struct{}` I mean *receive only*. Std don't have any package which allow use channel. You can access to channel only via method and this method return *receive only* channel. For example  in _context_ package
<https://github.com/golang/go/blob/master/src/context/context.go#L324>
or _Ticker_ and _After_ from _time_ package. 
Maybe while it's a fresh change we can change api?
# Also 
I would like to see the same approach for _Event()( <-chan Event)_ just as alternative. And recommendation in examples to use it. Of course a lot of  people already use raw _Event_ channel. It should be stay. Until 2.0.
Up to you! :-) 
The same approach with _Error_ chanel
