### ISSUE TITLE
Release tags not including the leading `v` are unreachable by Go modules

### ISSUE THREAD

**Issue by sevein** [radovskyb/watcher#60]
Hi @radovskyb. Thanks for making this project available to the public!

I've found one minor issue when importing `github.com/radovskyb/watcher` as a Go module. Go can't find releases tagged in this repo when the tag name does not include the leading `v` character. Namely: tags `1.0.3`, `1.0.4` and `1.0.5` are missing the leading `v` character. Go believes that `v1.0.2` is the latest release since that's the highest version within the subset where the the leading `v` character is present.

This is what I'm seeing:

```console
$ go mod init github.com/sevein/foobar
$ go get github.com/radovskyb/watcher@v1.0.5
go: finding github.com/radovskyb/watcher v1.0.5
go get github.com/radovskyb/watcher@v1.0.5: unknown revision v1.0.5
$ go get github.com/radovskyb/watcher
go: finding github.com/radovskyb/watcher v1.0.2
go: downloading github.com/radovskyb/watcher v1.0.2
```

Tagging 3818ec2 as `v1.0.5` (in addition to the existing tags) may be enough to solve the problem.

**Comment by radovskyb** [comment]
Hey @sevein,

Have you tried just calling the command like so:

go get github.com/radovskyb/watcher@1.0.5 (Without the `v`)?

It should work :)

**Comment by sevein** [comment]
Thanks @radovskyb. I tried that but then vgo doesn't understand it as a semantic version which is probably going to impact the [behaviour of `go get  -u`](https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies) later on as Go believes I'm just asking to import a specific commit instead of an actual release. I think that your example would be the equivalent of the following command:

    go get github.com/radovskyb/watcher@3818ec23ec59

So it's not that I can't import it, it's that Go's version selection system isn't going to take into account any of your releases missing the mandatory leading `v`. If you try the following:

    go get github.com/radovskyb/watcher

You'll be effectively importing `v1.0.2` because that's the most recent v1 release from Go's perspective. It's in their [docs](https://github.com/golang/go/wiki/Modules):

> Modules must be semantically versioned according to [semver](https://semver.org/) in the form `v(major).(minor).(patch)`, such as  `v0.1.0` or `v1.2.3`. The leading `v` is required. If using Git, [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) released commits with their versions. Public and private module repositories and proxies are becoming available (see FAQ [below](https://github.com/golang/go/wiki/Modules#are-there-always-on-module-repositories-and-enterprise-proxies)).

**Comment by radovskyb** [comment]
Thanks @sevein,

I actually didn't know that :P Hadn't read the `go mod` notes yet.

I'll update the latest tag to v1.0.5 for you! :D

**Comment by sevein** [comment]
Thank you, it works!
