### ISSUE TITLE
Missing Event.OldPath

### ISSUE THREAD

**Issue by coreybutler** [radovskyb/watcher#78]
The master branch (and therefore the godocs) contain [Event.OldPath](https://github.com/radovskyb/watcher/blob/master/watcher.go#L71), but the [tagged release (v1.0.6)](https://github.com/radovskyb/watcher/releases/tag/v1.0.6) does not. 

I kept scratching my head when coming across these compilation errors:

![image](https://user-images.githubusercontent.com/770982/63217002-105bea80-c104-11e9-976f-8968ce23f955.png)

You can see by downloading the zip file and looking at the extracted contents:

![image](https://user-images.githubusercontent.com/770982/63216966-86ac1d00-c103-11e9-9e9a-3e1267aa35a2.png)

@radovskyb Think you could publish a new release with these updates?

**Comment by Akumzy** [comment]
@coreybutler I don't think it has been merge to master branch

**Comment by coreybutler** [comment]
@Akumzy It has been merged to master. See [this line](https://github.com/radovskyb/watcher/blob/master/watcher.go#L71).

**Comment by radovskyb** [comment]
Hey @coreybutler. I've published release v1.0.7 :)

**Comment by coreybutler** [comment]
Thanks @radovskyb!
