### ISSUE TITLE
Ignore paths

### ISSUE THREAD

**Issue by ericmdantas** [radovskyb/watcher#8]
When watching folders recursively, there might be some folders where I don't want the watcher to touch. 

These folders can be `dependencies` (which were downloaded by some package manager), folders meant to be used as `example`, folders that keep the `app tests` (not the case in Go happens in mostly of other languages).

So, I think that we could have some way to ignore those paths, so we don't increase our slice of paths/files that's being watched without necessity.

### Example

For example, say that right now I'm using the watcher in a rather simple web app. In this app I have two folders that contain the libs used for both `development` (like tasks and suchs - that's in node_modules) and libs that I really use in the app (that's in bower_components).

The number of folders in `node_modules` is: 825. Inside each of these folders there's a bunch of other folders/files.

The number of folders in `bower_components` is: 27. Inside each of these, there are also a bunch of other folders/files.

So, when I watch the root of my app (which contains both of these folders), right off the bat, I'm watching thousands of stuff I either don't care or won't change - which makes the watcher take longer to report the events going on in the files I really want to watch.

I know I could solve that by specifying exactly what I want to watch, like: `w.Add("path_1")`, `w.Add("path_2")`, w.Add("path_3"), etc. But sometimes inside those paths there might be something I'd also like to ignore.

### Proprosal

Either refactor way `Options` work, using a real struct so the user can have something like this when creating a new watcher:

```go
opt := &Options{
   NonRecursive: true,
   Ignore: []string{"a", "b", "c", "d/f/g/h"},
   SomethingElse: false,
}

w := watcher.New(opt)
```

Or use the same approach, but not at the moment to create a watcher, but when the user wants to Add a path to be watched:

```go
w := watcher.New()

optPath1 := &Options{
   NonRecursive: true,
   Ignore: []string{"a"},
   SomethingElse: false,
}

optPath2 := &Options{
   NonRecursive: false,
   Ignore: []string{"a", "b", "c", "d/f/g/h"},
}

optPath3 := &Options{
   Ignore: []string{"xyz/123"},
}

w.Add("path_1", optPath1)
w.Add("path_2", optPath2)
w.Add("path_3", optPath3)
```

**Comment by radovskyb** [comment]
Hey @ericmdantas :)

I definitely want to add the ability to ignore specific paths and also possibly specific extensions, so I am going to add this to `watcher`.

I did actually want to rewrite the way options were handled with `watcher` anyway so using a struct might be a good idea regardless of the main reason for this proposal. 

Having said that, just like with adding adding a `Close` method, when I rewrite the main watching loop and the `ListFiles` function, it will also affect the way things like ignoring paths are handled, so I think for now, I might simply add a function such as `func (w *Watcher) Ignore(paths ...string)`, but once I've rewritten the parts that I wanted changed, I'll either keep it the way it is if it works well, or reconsider something like your proposal for it, as well as adding in the `Close` method.

Another great suggestion as always, thanks!

**Comment by radovskyb** [comment]
I've added a simple `Ignore` method for now so hopefully I didn't rush it and it works the way it's meant to :P Either way though, it will still need to be rewritten once I rewrite the other things anyway.

For now I don't think it makes sense to change the way how the options work since with the suggested way, race conditions could occur if the options are modified after they've been set and the calling `Start`, whereas at the moment it's immutable and since the ignored paths are separated from the options, adding ignored paths is protected against race conditions even after the watching process has started and more ignored paths can be added at any time..

I still definitely think a lot of `watcher` needs some more idiomatic rewriting to avoid these issues though so when I'm not so busy I'll have to think a lot of this stuff through...

**Comment by ericmdantas** [comment]
Thanks, @radovskyb. I'll give it a try.

PS: About the racing conditions, instead of passing a pointer, what if we pass a value?

**Comment by ericmdantas** [comment]
As the the new method, it seems to be working as expected, thanks once again :+1:

Feel free to close the issue, if you feel like it.

**Comment by radovskyb** [comment]
Hey @ericmdantas, I was thinking about passing by value but things like maps and slices are still references anyway so that could cause the same issue possibly.. 

I'm not even sure if I've over thought it or not :P Either way, I'll refactor it eventually.
